### ISSUE TITLE
testing: transaction encoding and signing

### ISSUE THREAD

**Issue by pcppcp** [AnyLedger/anyledger-wallet#51]
Create tests for the `eth/transaction.h` module.

The tests should initialize `transaction_t` data structure, call `tx_encode()` and compare the output with a known signed transaction.

Also see: [test_tx](https://github.com/AnyLedger/anyledger-wallet/blob/master/tests/test_tx.cpp)

Test data generator (Python3)

```Python
from eth_account.internal.transactions import UnsignedTransaction, Transaction
from eth_utils import decode_hex, encode_hex, to_checksum_address
from coincurve import PrivateKey
import rlp
tx = UnsignedTransaction(1, 1, 300, decode_hex(to_checksum_address('0x7e5f4552091a69125d5dfcb7b8c2659029395bdf')), 1, b'')
print("unsigned: " + encode_hex(rlp.encode(tx)))
# sign (for key 000.00001)
k = PrivateKey.from_hex(31*'00' + '01')
sign = k.sign_recoverable(rlp.encode(tx))
(r, s, v) = int.from_bytes(sign[:32], byteorder='big'), int.from_bytes(sign[32:64], byteorder='big'), sign[64]
signed_tx = Transaction(*tx.as_dict().values(), r, s, v)
print("signed: " + encode_hex(rlp.encode(signed_tx)))
```

**Comment by vishav26** [comment]
Hi @pcppcp @lorepieri8 ,

I successfully built and compiled the code and run test_tx by removing the #if from the code. There was a run-time error due to Stack buffer overflow because ENCODED_TX_BUFSIZE was 100 but the data length along with signature is 112. I changed it to 200. 
The test case looks good to me. What other things are expected from me to add to the test case?

Thanks & Regards
Vishav
